# Generated by Django 3.2.5 on 2021-08-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20210619_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
